using System;
using BlasII.Framework.WeaponEvents.Constants;
using BlasII.Framework.WeaponEvents.HandlersManagers;
using BlasII.ModdingAPI;
using Il2Cpp;
using Il2CppGame.Components.Attack;
using Il2CppTGK.Game.Components.Attack;
using Il2CppTGK.Game.Components;
using Il2CppTGK.Game.Components.Attack.Data;

namespace BlasII.Framework.WeaponEvents;

/// <summary>
/// This mod allows other developers to execute code at specific events
/// generated by the weapons.
///
/// It also permits you to change the state of current weapons (like setting
/// Veredicto on fire, or setting the blood pact jauge to a certain value).
///
/// For example, you could set Veredicto on fire whenever the player hits an
/// enemy with the second hit of Veredicto's mid air normal attack.
/// </summary>
public class WeaponEventsFramework : BlasIIMod
{
	/* Handlers managers */

	/// <summary>Manages the handlers for any weapons</summary>
	public WeaponHandlersManager WeaponHandlersManager { get; private set; }

	/// <summary>Manages the handlers for Veredicto</summary>
	public CenserHandlersManager CenserHandlersManager { get; private set; }

	/// <summary>Manages the handlers for Saarmiento y Centella</summary>
	public RapierHandlersManager RapierHandlersManager { get; private set; }

	/// <summary>Manages the handlers for Ruego al Alba</summary>
	public BladeHandlersManager BladeHandlersManager { get; private set; }

	/// <summary>Manages the handlers for Mea Culpa</summary>
	public MeaCulpaHandlersManager MeaCulpaHandlersManager { get; private set; }


	/* Quick access game objects */

	/// <summary>Represents the currently equipped weapon.</summary>
	public Weapon CurrentWeapon { get; protected internal set; } = Weapon.NONE;

	/// <summary>Represents the currently equipped weapon.</summary>
	public UIWeaponController UIWeaponController { get; protected internal set; } = null;

	/// <summary>Object that manages the state of Veredicto and the consumption of fervour.</summary>
	public CenserIgniter CenserIgniter { get; protected internal set; } = null;

	/// <summary>Represents the current state of Veredicto.</summary>
	public bool IsCenserIgnited { get; protected internal set; } = false;

	/// <summary>Object that manages the filling of Sarmiento y Centalla's indicators.</summary>
	public RapierTrueSkillFiller RapierTrueSkillFiller { get; protected internal set; } = null;

	/// <summary>Object that manages the filling of Ruego al Alba's jauge.</summary>
	public BladeBerserkModeFiller BladeBerserkModeFiller { get; protected internal set; } = null;

	/// <summary>Object that manages the filling of Mea Culpa's jauge.</summary>
	public MeaCulpaBerserkModeFiller MeaCulpaBerserkModeFiller { get; protected internal set; } = null;


	/* Methods */

	/// <summary>
	/// Initializes a new instance of the framework.
	/// It creates empty lists of handlers managers for each weapon kind (even
	/// the common weapon manager).
	/// </summary>
    internal WeaponEventsFramework() :
		base(ModInfo.MOD_ID, ModInfo.MOD_NAME, ModInfo.MOD_AUTHOR, ModInfo.MOD_VERSION)
	{
		WeaponHandlersManager = new WeaponHandlersManager();
		CenserHandlersManager = new CenserHandlersManager();
		RapierHandlersManager = new RapierHandlersManager();
		BladeHandlersManager = new BladeHandlersManager();
		MeaCulpaHandlersManager = new MeaCulpaHandlersManager();
	}

	/// <summary>
	/// Called after the mod has been loaded and before the game starts.
	/// </summary>
    protected override void OnInitialize()
    {
		WeaponHandlersManager.RegisterAllHandlers();
		CenserHandlersManager.RegisterAllHandlers();
		RapierHandlersManager.RegisterAllHandlers();
		BladeHandlersManager.RegisterAllHandlers();
		MeaCulpaHandlersManager.RegisterAllHandlers();
    }

	/// <summary>
	/// Called when the current weapon is being withdrawn and will soon be
	/// replaced by another weapon.
	/// This is part of a two step weapon change, where this is the first part.
	/// This is to make sure the code executed when a weapon is unequipped is
	/// executed before the weapon is no longer in hands.
	/// </summary>
	protected internal void UnequipCurrentWeapon()
	{
		WeaponHandlersManager.Handlers.ForEach(handler => handler.OnUnequip());

		switch (Main.WeaponEventsFramework.CurrentWeapon)
		{
			case Weapon.BLADE:
				BladeHandlersManager.Handlers.ForEach(handler => handler.OnUnequip());
				break;
			case Weapon.CENSER:
				CenserHandlersManager.Handlers.ForEach(handler => handler.OnUnequip());
				Main.WeaponEventsFramework.IsCenserIgnited = false;
				break;
			case Weapon.RAPIER:
				RapierHandlersManager.Handlers.ForEach(handler => handler.OnUnequip());
				break;
			case Weapon.MEA_CULPA:
				MeaCulpaHandlersManager.Handlers.ForEach(handler => handler.OnUnequip());
				break;
		}
	}

	/// <summary>
	/// Called when a new weapon is being drawn.
	/// This is part of a two step weapon change, where this is the second part.
	/// This is to make sure the code executed when a new weapon is equipped is
	/// executed after the weapon is in hands.
	/// </summary>
	protected internal void EquipNewWeapon(int id)
	{
		Weapon weapon = (Weapon) id;
		if (!Enum.IsDefined(typeof(Weapon), weapon))
		{
			ModLog.Error($"Error: Unknown weapon ID: {id}");
			return;
		}

		CurrentWeapon = weapon;
		WeaponHandlersManager.Handlers.ForEach(handler => handler.OnEquip());

		switch (weapon)
		{
			case Weapon.BLADE:
				BladeHandlersManager.Handlers.ForEach(handler => handler.OnEquip());
				break;
			case Weapon.CENSER:
				CenserHandlersManager.Handlers.ForEach(handler => handler.OnEquip());
				break;
			case Weapon.RAPIER:
				RapierHandlersManager.Handlers.ForEach(handler => handler.OnEquip());
				break;
			case Weapon.MEA_CULPA:
				MeaCulpaHandlersManager.Handlers.ForEach(handler => handler.OnEquip());
				break;
		}
	}

	/// <summary>
	/// The global handler for when an attack is produced.
	/// This method is called whenever the player attacks, no matter the weapon
	/// in use or whether the attack hits an enemy or not.
	/// It proceeds to call the corresponding handler managers depending on the
	/// weapon.
	/// </summary>
	protected internal void HandleAttack(AttackID id)
	{
		WeaponHandlersManager.HandleAttack(id);
		switch (CurrentWeapon)
		{
			case Weapon.NONE:
				ModLog.Error("Error: Attack occured while no weapon is equipped!");
				break;
			case Weapon.CENSER:
				CenserHandlersManager.HandleAttack(id);
				break;
			case Weapon.RAPIER:
				RapierHandlersManager.HandleAttack(id);
				break;
			case Weapon.BLADE:
				BladeHandlersManager.HandleAttack(id);
				break;
			case Weapon.MEA_CULPA:
				MeaCulpaHandlersManager.HandleAttack(id);
				break;
		}
	}

	/// <summary>
	/// The global handler for when an attack is produced.
	/// This method is called whenever the player attacks, no matter the weapon
	/// in use, but only if the attack hits an enemy.
	/// It proceeds to call the corresponding handler managers depending on the
	/// weapon.
	/// </summary>
	protected internal void HandleAttackHit(AttackInfo info)
	{
		if (info.attackReceiver == null)
		{
			return;
		}

		WeaponHandlersManager.HandleAttackHit(info);
		switch (CurrentWeapon)
		{
			case Weapon.NONE:
				ModLog.Error("Error: Attack occured while no weapon is equipped!");
				break;
			case Weapon.CENSER:
				CenserHandlersManager.HandleAttackHit(info);
				break;
			case Weapon.RAPIER:
				RapierHandlersManager.HandleAttackHit(info);
				break;
			case Weapon.BLADE:
				BladeHandlersManager.HandleAttackHit(info);
				break;
			case Weapon.MEA_CULPA:
				MeaCulpaHandlersManager.HandleAttackHit(info);
				break;
		}
	}

	/// <summary>
	/// The global handler for when the player rests at a prie dieu.
	/// It proceeds to call the corresponding handler managers depending on the
	/// weapon.
	/// </summary>
	protected internal void HandleRestAtPrieDieu()
	{
		WeaponHandlersManager.HandleRestAtPrieDieu();
		switch (CurrentWeapon)
		{
			case Weapon.NONE:
				ModLog.Error("Error: Attack occured while no weapon is equipped!");
				break;
			case Weapon.CENSER:
				CenserHandlersManager.HandleRestAtPrieDieu();
				break;
			case Weapon.RAPIER:
				RapierHandlersManager.HandleRestAtPrieDieu();
				break;
			case Weapon.BLADE:
				BladeHandlersManager.HandleRestAtPrieDieu();
				break;
			case Weapon.MEA_CULPA:
				MeaCulpaHandlersManager.HandleRestAtPrieDieu();
				break;
		}
	}
}
