using BlasII.Framework.WeaponEvents.Constants;
using BlasII.Framework.WeaponEvents.Events;
using Il2CppTGK.Game.Components.Attack.Data;
using System;

namespace BlasII.Framework.WeaponEvents.HandlersManagers;


/// <summary>
/// Manages the handlers for Mea Culpa.
/// </summary>
public class MeaCulpaHandlersManager : AbstractHandlersManager<MeaCulpaHandler>
{
	/// <summary>Calls the base class constructor.</summary>
	public MeaCulpaHandlersManager() : base("Mea Culpa") {}

	/// <summary>
	/// Handles Mea Culpa's attacks, and calls the corresponding managed
	/// handlers methods.
	/// </summary>
	public override void HandleAttack(AttackID id)
	{
		Handlers.ForEach(handler => handler.OnAttack(id));

		MeaCulpaAttackID attack = (MeaCulpaAttackID) id.id;
		if (!Enum.IsDefined(typeof(MeaCulpaAttackID), attack))
		{
			LogUnknownAttackIDError(id);
			return;
		}

		switch (attack)
		{
			case MeaCulpaAttackID.COMBO_1:
			case MeaCulpaAttackID.COMBO_1_PROJECTILE_SPAWNER:
			case MeaCulpaAttackID.COMBO_2:
			case MeaCulpaAttackID.COMBO_3:
			case MeaCulpaAttackID.COMBO_3_ASCENDING:
			case MeaCulpaAttackID.COMBO_3_SPIN:
			case MeaCulpaAttackID.COMBO_4:
				HandleComboAttack(attack);
				break;
			case MeaCulpaAttackID.CROUCH:
				break;
			case MeaCulpaAttackID.MIDAIR_COMBO_1:
			case MeaCulpaAttackID.MIDAIR_COMBO_1_PROJECTILE_SPAWNER:
			case MeaCulpaAttackID.MIDAIR_COMBO_2:
				HandleMidairAttack(attack);
				break;
			case MeaCulpaAttackID.UP_SLASH:
			case MeaCulpaAttackID.UP_SLASH_PROJECTILE_SPAWNER:
			case MeaCulpaAttackID.MIDAIR_UP_SLASH:
			case MeaCulpaAttackID.MIDAIR_UP_SLASH_PROJECTILE_SPAWNER:
				HandleUpSlashAttack(attack);
				break;
			case MeaCulpaAttackID.NORMAL_RETRIBUTION:
			case MeaCulpaAttackID.PERFECT_RETRIBUTION:
				HandleRetribution(attack);
				break;
			case MeaCulpaAttackID.PHANTOM_PROJECTILE:
				break;
			case MeaCulpaAttackID.LOWER_PLUNGING_STRIKE:
			case MeaCulpaAttackID.HIGH_PLUNGING_STRIKE:
				HandlePlungingStrike(attack);
				break;
			case MeaCulpaAttackID.CHARGED:
				Handlers.ForEach(handler => handler.OnChargedAttack());
				break;
			case MeaCulpaAttackID.THRUST:
				Handlers.ForEach(handler => handler.OnThrustAttack());
				break;
			case MeaCulpaAttackID.REMORSE_START:
				Handlers.ForEach(handler => handler.OnRemorseStart());
				break;
			default:
				LogUnsupportedAttackIDError(id);
				break;
		}
	}

	/// <summary>
	/// Handles Mea Culpa's attacks when they hit an enemy, and calls the
	/// corresponding managed handlers methods.
	/// </summary>
	public override void HandleAttackHit(AttackInfo info)
	{
		Handlers.ForEach(handler => handler.OnAttackHit(info));

		MeaCulpaAttackID attack = (MeaCulpaAttackID) info.attackID.id;
		if (!Enum.IsDefined(typeof(MeaCulpaAttackID), attack))
		{
			LogUnknownAttackIDError(info.attackID);
			return;
		}

		switch (attack)
		{
			case MeaCulpaAttackID.COMBO_1:
			case MeaCulpaAttackID.COMBO_1_PROJECTILE_SPAWNER:
			case MeaCulpaAttackID.COMBO_2:
			case MeaCulpaAttackID.COMBO_3:
			case MeaCulpaAttackID.COMBO_3_ASCENDING:
			case MeaCulpaAttackID.COMBO_3_SPIN:
			case MeaCulpaAttackID.COMBO_4:
				HandleComboAttackHit(attack, info);
				break;
			case MeaCulpaAttackID.CROUCH:
				break;
			case MeaCulpaAttackID.MIDAIR_COMBO_1:
			case MeaCulpaAttackID.MIDAIR_COMBO_1_PROJECTILE_SPAWNER:
			case MeaCulpaAttackID.MIDAIR_COMBO_2:
				HandleMidairAttackHit(attack, info);
				break;
			case MeaCulpaAttackID.UP_SLASH:
			case MeaCulpaAttackID.UP_SLASH_PROJECTILE_SPAWNER:
			case MeaCulpaAttackID.MIDAIR_UP_SLASH:
			case MeaCulpaAttackID.MIDAIR_UP_SLASH_PROJECTILE_SPAWNER:
				HandleUpSlashAttackHit(attack, info);
				break;
			case MeaCulpaAttackID.NORMAL_RETRIBUTION:
			case MeaCulpaAttackID.PERFECT_RETRIBUTION:
				HandleRetributionHit(attack, info);
				break;
			case MeaCulpaAttackID.PHANTOM_PROJECTILE:
				Handlers.ForEach(handler => handler.OnPhantomProjectileHit(info));
				break;
			case MeaCulpaAttackID.LOWER_PLUNGING_STRIKE:
			case MeaCulpaAttackID.HIGH_PLUNGING_STRIKE:
				HandlePlungingStrikeHit(attack, info);
				break;
			case MeaCulpaAttackID.CHARGED:
				Handlers.ForEach(handler => handler.OnChargedAttackHit(info));
				break;
			case MeaCulpaAttackID.THRUST:
				Handlers.ForEach(handler => handler.OnThrustAttackHit(info));
				break;
			case MeaCulpaAttackID.REMORSE_START:
				Handlers.ForEach(handler => handler.OnRemorseStartHit(info));
				break;
			default:
				LogUnsupportedAttackIDError(info.attackID);
				break;
		}
	}

	/// <summary>
	/// Handles Mea Culpa's combo attacks, generated by the player when
	/// continuously attacking on the ground.
	/// </summary>
	public void HandleComboAttack(MeaCulpaAttackID attack)
	{
		Handlers.ForEach(handler => handler.OnCombo(attack));
		switch (attack)
		{
			case MeaCulpaAttackID.COMBO_1:
				Handlers.ForEach(handler => handler.OnCombo1());
				Handlers.ForEach(handler => handler.OnCombo1NoProjectile());
				break;
			case MeaCulpaAttackID.COMBO_1_PROJECTILE_SPAWNER:
				Handlers.ForEach(handler => handler.OnCombo1());
				Handlers.ForEach(handler => handler.OnCombo1ProjectileSpawner());
				Handlers.ForEach(handler => handler.OnProjectileSpawnerAttack(attack));
				break;
			case MeaCulpaAttackID.COMBO_2:
				Handlers.ForEach(handler => handler.OnCombo2());
				break;
			case MeaCulpaAttackID.COMBO_3:
				Handlers.ForEach(handler => handler.OnCombo3());
				break;
			case MeaCulpaAttackID.COMBO_3_ASCENDING:
				Handlers.ForEach(handler => handler.OnCombo3Ascending());
				break;
			case MeaCulpaAttackID.COMBO_3_SPIN:
				Handlers.ForEach(handler => handler.OnCombo3Spin());
				break;
			case MeaCulpaAttackID.COMBO_4:
				Handlers.ForEach(handler => handler.OnCombo4());
				break;
		}
	}

	/// <summary>
	/// Handles Mea Culpa's combo attacks when they hit an enemy, generated by
	/// the player when continuously attacking on the ground.
	/// </summary>
	public void HandleComboAttackHit(MeaCulpaAttackID attack, AttackInfo info)
	{
		Handlers.ForEach(handler => handler.OnComboHit(attack, info));
		switch (attack)
		{
			case MeaCulpaAttackID.COMBO_1:
				Handlers.ForEach(handler => handler.OnCombo1Hit(info));
				Handlers.ForEach(handler => handler.OnCombo1NoProjectileHit(info));
				break;
			case MeaCulpaAttackID.COMBO_1_PROJECTILE_SPAWNER:
				Handlers.ForEach(handler => handler.OnCombo1Hit(info));
				Handlers.ForEach(handler => handler.OnCombo1ProjectileSpawnerHit(info));
				Handlers.ForEach(handler => handler.OnProjectileSpawnerAttackHit(attack, info));
				break;
			case MeaCulpaAttackID.COMBO_2:
				Handlers.ForEach(handler => handler.OnCombo2Hit(info));
				break;
			case MeaCulpaAttackID.COMBO_3:
				Handlers.ForEach(handler => handler.OnCombo3Hit(info));
				break;
			case MeaCulpaAttackID.COMBO_3_ASCENDING:
				Handlers.ForEach(handler => handler.OnCombo3AscendingHit(info));
				break;
			case MeaCulpaAttackID.COMBO_3_SPIN:
				Handlers.ForEach(handler => handler.OnCombo3SpinHit(info));
				break;
			case MeaCulpaAttackID.COMBO_4:
				Handlers.ForEach(handler => handler.OnCombo4Hit(info));
				break;
			default:
				LogUnsupportedAttackIDError(info.attackID);
				break;
		}
	}

	/// <summary>
	/// Handles Mea Culpa's midair attacks, generated by the player when
	/// attacking while in the air.
	/// </summary>
	public void HandleMidairAttack(MeaCulpaAttackID attack)
	{
		Handlers.ForEach(handler => handler.OnMidairSlash(attack));
		switch (attack)
		{
			case MeaCulpaAttackID.MIDAIR_COMBO_1:
				Handlers.ForEach(handler => handler.OnMidairSlash1());
				Handlers.ForEach(handler => handler.OnMidairSlash1NoProjectile());
				break;
			case MeaCulpaAttackID.MIDAIR_COMBO_1_PROJECTILE_SPAWNER:
				Handlers.ForEach(handler => handler.OnMidairSlash1());
				Handlers.ForEach(handler => handler.OnMidairSlash1ProjectileSpawner());
				Handlers.ForEach(handler => handler.OnProjectileSpawnerAttack(attack));
				break;
			case MeaCulpaAttackID.MIDAIR_COMBO_2:
				Handlers.ForEach(handler => handler.OnMidairSlash2());
				break;
		}
	}

	/// <summary>
	/// Handles Mea Culpa's midair attacks when they hit an enemy, generated by
	/// the player when attacking while in the air.
	/// </summary>
	public void HandleMidairAttackHit(MeaCulpaAttackID attack, AttackInfo info)
	{
		Handlers.ForEach(handler => handler.OnMidairSlashHit(attack, info));
		switch (attack)
		{
			case MeaCulpaAttackID.MIDAIR_COMBO_1:
				Handlers.ForEach(handler => handler.OnMidairSlash1Hit(info));
				Handlers.ForEach(handler => handler.OnMidairSlash1NoProjectileHit(info));
				break;
			case MeaCulpaAttackID.MIDAIR_COMBO_1_PROJECTILE_SPAWNER:
				Handlers.ForEach(handler => handler.OnMidairSlash1Hit(info));
				Handlers.ForEach(handler => handler.OnMidairSlash1ProjectileSpawnerHit(info));
				Handlers.ForEach(handler => handler.OnProjectileSpawnerAttackHit(attack, info));
				break;
			case MeaCulpaAttackID.MIDAIR_COMBO_2:
				Handlers.ForEach(handler => handler.OnMidairSlash2Hit(info));
				break;
			default:
				LogUnsupportedAttackIDError(info.attackID);
				break;
		}
	}

	/// <summary>
	/// Handles Mea Culpa's up slash attacks, generated by the player when
	/// attacking upward.
	/// </summary>
	public void HandleUpSlashAttack(MeaCulpaAttackID attack)
	{
		Handlers.ForEach(handler => handler.OnUpSlashAttack());
		switch (attack)
		{
			case MeaCulpaAttackID.UP_SLASH:
				Handlers.ForEach(handler => handler.OnUpSlashAttack());
				break;
			case MeaCulpaAttackID.MIDAIR_UP_SLASH:
				Handlers.ForEach(handler => handler.OnMidairUpSlashAttack());
				break;
			case MeaCulpaAttackID.UP_SLASH_PROJECTILE_SPAWNER:
				Handlers.ForEach(handler => handler.OnUpSlashAttack());
				Handlers.ForEach(handler => handler.OnProjectileSpawnerAttack(attack));
				break;
			case MeaCulpaAttackID.MIDAIR_UP_SLASH_PROJECTILE_SPAWNER:
				Handlers.ForEach(handler => handler.OnMidairUpSlashAttack());
				Handlers.ForEach(handler => handler.OnProjectileSpawnerAttack(attack));
				break;
		}
	}

	/// <summary>
	/// Handles Mea Culpa's up slash attacks when they hit an enemy, generated
	/// by the player when attacking upward.
	/// </summary>
	public void HandleUpSlashAttackHit(MeaCulpaAttackID attack, AttackInfo info)
	{
		Handlers.ForEach(handler => handler.OnUpSlashAttackHit(info));
		switch (attack)
		{
			case MeaCulpaAttackID.UP_SLASH:
				Handlers.ForEach(handler => handler.OnUpSlashAttackHit(info));
				break;
			case MeaCulpaAttackID.MIDAIR_UP_SLASH:
				Handlers.ForEach(handler => handler.OnMidairUpSlashAttackHit(info));
				break;
			case MeaCulpaAttackID.UP_SLASH_PROJECTILE_SPAWNER:
				Handlers.ForEach(handler => handler.OnUpSlashAttackHit(info));
				Handlers.ForEach(handler => handler.OnProjectileSpawnerAttackHit(attack, info));
				break;
			case MeaCulpaAttackID.MIDAIR_UP_SLASH_PROJECTILE_SPAWNER:
				Handlers.ForEach(handler => handler.OnMidairUpSlashAttackHit(info));
				Handlers.ForEach(handler => handler.OnProjectileSpawnerAttackHit(attack, info));
				break;
			default:
				LogUnsupportedAttackIDError(info.attackID);
				break;
		}
	}

	/// <summary>
	/// Handles Mea Culpa's retributions, generated by the player when parrying
	/// an enemy attack and reposting.
	/// </summary>
	public void HandleRetribution(MeaCulpaAttackID attack)
	{
		Handlers.ForEach(handler => handler.OnRetribution(attack));
		switch (attack)
		{
			case MeaCulpaAttackID.NORMAL_RETRIBUTION:
				Handlers.ForEach(handler => handler.OnNormalRetribution());
				break;
			case MeaCulpaAttackID.PERFECT_RETRIBUTION:
				Handlers.ForEach(handler => handler.OnPerfectRetribution());
				break;
		}
	}

	/// <summary>
	/// Handles Mea Culpa's retributions when they hit an enemy, generated by
	/// the player when parrying an enemy attack and reposting.
	/// </summary>
	public void HandleRetributionHit(MeaCulpaAttackID attack, AttackInfo info)
	{
		Handlers.ForEach(handler => handler.OnRetributionHit(attack, info));
		switch (attack)
		{
			case MeaCulpaAttackID.NORMAL_RETRIBUTION:
				Handlers.ForEach(handler => handler.OnNormalRetributionHit(info));
				break;
			case MeaCulpaAttackID.PERFECT_RETRIBUTION:
				Handlers.ForEach(handler => handler.OnPerfectRetributionHit(info));
				break;
			default:
				LogUnsupportedAttackIDError(info.attackID);
				break;
		}
	}

	/// <summary>
	/// Handles Mea Culpa's plunging strikes, generated by the player when
	/// attacking down while in the air.
	/// </summary>
	public void HandlePlungingStrike(MeaCulpaAttackID attack)
	{
		Handlers.ForEach(handler => handler.OnPlungingStrike(attack));
		switch (attack)
		{
			case MeaCulpaAttackID.LOWER_PLUNGING_STRIKE:
				Handlers.ForEach(handler => handler.OnLowerPlungingStrike());
				break;
			case MeaCulpaAttackID.HIGH_PLUNGING_STRIKE:
				Handlers.ForEach(handler => handler.OnHighPlungingStrike());
				break;
		}
	}

	/// <summary>
	/// Handles Mea Culpa's plunging strikes when they hit an enemy, generated
	/// by the player when attacking down while in the air.
	/// </summary>
	public void HandlePlungingStrikeHit(MeaCulpaAttackID attack, AttackInfo info)
	{
		Handlers.ForEach(handler => handler.OnPlungingStrikeHit(attack, info));
		switch (attack)
		{
			case MeaCulpaAttackID.LOWER_PLUNGING_STRIKE:
				Handlers.ForEach(handler => handler.OnLowerPlungingStrikeHit(info));
				break;
			case MeaCulpaAttackID.HIGH_PLUNGING_STRIKE:
				Handlers.ForEach(handler => handler.OnHighPlungingStrikeHit(info));
				break;
			default:
				LogUnsupportedAttackIDError(info.attackID);
				break;
		}
	}

	/// <summary>
	/// When the Mea Culpa's phantom projectils is ready again, calls the
	/// managed handlers corresponding method.
	/// </summary>
	public void HandlePhantomProjectileReady()
	{
		Handlers.ForEach(handler => handler.OnPhantomProjectileReady());
	}
}

